name: PROGRA_I_2024
channels:
  - defaults
  - conda-forge
dependencies:
  - archspec=0.2.1
  - boltons=23.0.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - conda=24.1.2
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=23.12.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - cryptography=41.0.7
  - distro=1.8.0
  - expat=2.5.0
  - fmt=9.1.0
  - idna=3.4
  - jsonpatch=1.32
  - jsonpointer=2.1
  - libarchive=3.6.2
  - libcurl=8.5.0
  - libffi=3.4.4
  - libiconv=1.16
  - libmamba=1.5.3
  - libmambapy=1.5.3
  - libsolv=0.7.24
  - libssh2=1.10.0
  - libxml2=2.10.4
  - lz4-c=1.9.4
  - menuinst=2.0.2
  - openssl=3.0.13
  - packaging=23.1
  - pcre2=10.42
  - pip=23.3.1
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.12.1
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.31.0
  - ruamel.yaml=0.17.21
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tqdm=4.65.0
  - truststore=0.8.0
  - urllib3=2.1.0
  - wheel=0.41.2
  - xz=5.4.5
  - yaml-cpp=0.8.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.5
  - pip:
      - antiorm==1.2.1
      - click==8.1.7
      - contourpy==1.2.1
      - ctkmessagebox==2.5
      - ctktable==0.7
      - ctktablerowselector==1.0.1
      - customtkinter==5.2.2
      - cycler==0.12.1
      - darkdetect==0.8.0
      - db==0.1.1
      - db-sqlite3==0.0.1
      - decorator==5.1.1
      - fonttools==4.53.0
      - future==1.0.0
      - geocoder==1.38.1
      - kiwisolver==1.4.5
      - matplotlib==3.9.0
      - numpy==1.26.4
      - pandas==2.2.2
      - pillow==10.3.0
      - pyparsing==3.1.2
      - pyperclip==1.8.2
      - pyproj==3.6.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - ratelim==0.1.6
      - six==1.16.0
      - tkintermapview==1.29
      - tzdata==2024.1
